import tempfile
import unittest
from pathlib import Path

import round_2_solutions as s


class StringSolutionTests(unittest.TestCase):
    def test_string_questions(self):
        self.assertEqual(s.strings_01_reverse("rudder"), "red dur".replace(" ", ""))
        self.assertTrue(s.strings_02_is_palindrome("A man, a plan, a canal: Panama!"))
        self.assertEqual(s.strings_03_vowel_consonant_counts("Hello, 123"), (2, 3))
        self.assertTrue(s.strings_04_are_anagrams("Dormitory", "Dirty room!!"))
        self.assertEqual(s.strings_05_character_frequencies("aba"), {"a": 2, "b": 1})
        self.assertEqual(s.strings_06_first_non_repeating("swiss"), "w")
        self.assertEqual(s.strings_07_first_repeating("abca"), "a")
        self.assertEqual(s.strings_08_reverse_word_order("one   two"), "two one")
        self.assertEqual(s.strings_09_reverse_each_word("one two"), "eno owt")
        self.assertEqual(s.strings_10_compress_runs("aaabbc"), "a3b2c1")
        self.assertEqual(s.strings_11_decompress_runs("a3b2c1"), "aaabbc")
        self.assertEqual(s.strings_12_remove_duplicate_characters("banana"), "ban")
        self.assertEqual(s.strings_13_longest_word("one longest"), "longest")
        self.assertEqual(s.strings_14_word_count("  one   two "), 2)
        self.assertTrue(s.strings_15_is_pangram("The quick brown fox jumps over the lazy dog"))
        self.assertEqual(s.strings_16_swap_case_manually("Ab!"), "aB!")
        self.assertEqual(s.strings_17_capitalize_words("hELLO wORLD"), "Hello World")
        self.assertEqual(s.strings_18_most_frequent_character("abaca"), "a")
        self.assertEqual(s.strings_19_longest_common_prefix(["flower", "flow", "flight"]), "fl")
        self.assertEqual(s.strings_20_keep_only_letters_and_digits("a b-1!"), "ab1")
        self.assertEqual(s.strings_21_character_categories("Aa1!"), {
            "uppercase": 1, "lowercase": 1, "digits": 1, "special": 1
        })
        self.assertTrue(s.strings_22_contains_only_digits("0123"))
        self.assertEqual(s.strings_23_replace_vowels("Apple"), "*ppl*")
        self.assertTrue(s.strings_24_is_rotation("abcd", "cdab"))
        self.assertEqual(s.strings_25_all_substrings("ab"), ["a", "ab", "b"])
        self.assertEqual(s.strings_26_characters_at_even_indexes("abcdef"), "ace")
        self.assertEqual(s.strings_27_longest_unique_substring_length("abcabcbb"), 3)
        self.assertTrue(s.strings_28_brackets_balanced("([]{})"))
        self.assertEqual(s.strings_29_ascii_codes("A"), [65])
        self.assertEqual(s.strings_29_from_ascii_codes([65]), "A")
        self.assertEqual(s.strings_30_words_with_lengths("a bb"), [("a", 1), ("bb", 2)])


class ListSolutionTests(unittest.TestCase):
    def test_list_questions(self):
        self.assertEqual(s.lists_01_min_max([2, 1, 3]), (1, 3))
        self.assertEqual(s.lists_02_second_largest([5, 5, 4, 3]), 4)
        self.assertEqual(s.lists_03_third_largest([5, 4, 3]), 3)
        self.assertEqual(s.lists_04_sort_ascending([3, 1, 2]), [1, 2, 3])
        self.assertEqual(s.lists_05_sort_descending([3, 1, 2]), [3, 2, 1])
        self.assertEqual(s.lists_06_remove_duplicates([1, 2, 1]), [1, 2])
        self.assertEqual(s.lists_07_rotate_right(range(4), 1), [3, 0, 1, 2])
        self.assertEqual(s.lists_08_rotate_left([0, 1, 2, 3], 1), [1, 2, 3, 0])
        self.assertEqual(s.lists_09_two_sum_indexes([2, 7, 11], 9), (0, 1))
        self.assertEqual(s.lists_10_missing_number([1, 2, 4], 4), 3)
        self.assertEqual(s.lists_11_move_zeros_to_end([0, 1, 0, 2]), [1, 2, 0, 0])
        self.assertEqual(s.lists_12_maximum_subarray_sum([-2, 1, -3, 4, -1, 2, 1]), 6)
        self.assertEqual(s.lists_13_merge_sorted([1, 3], [2, 4]), [1, 2, 3, 4])
        self.assertEqual(s.lists_14_binary_search([1, 3, 5], 3), 1)
        self.assertEqual(s.lists_15_duplicates([1, 2, 1, 2, 1]), [1, 2])
        self.assertEqual(s.lists_16_most_frequent([2, 1, 2, 1]), 2)
        self.assertEqual(s.lists_17_count_pairs_with_sum([1, 1, 2, 2], 3), 4)
        self.assertEqual(s.lists_18_even_and_odd_indexes([1, 2, 3]), ([1, 3], [2]))
        values = [1, 2, 3]
        self.assertIsNone(s.lists_19_reverse_in_place(values))
        self.assertEqual(values, [3, 2, 1])
        self.assertTrue(s.lists_20_is_sorted_ascending([1, 1, 2]))
        self.assertEqual(s.lists_21_sum_and_average([1, 2, 3]), (6, 2))
        self.assertEqual(s.lists_22_separate_even_odd([1, 2, 3]), ([2], [1, 3]))
        self.assertEqual(s.lists_23_common_elements([1, 2, 1], [1, 3]), [1])
        self.assertEqual(s.lists_24_first_not_in_second([1, 2, 2], [2]), [1])
        self.assertEqual(s.lists_25_union_and_intersection([1, 2], [2, 3]), ([1, 2, 3], [2]))
        self.assertEqual(s.lists_26_running_sum([1, 2, 3]), [1, 3, 6])
        self.assertEqual(s.lists_27_longest_increasing_run([1, 2, 1, 3, 4]), [1, 3, 4])
        self.assertEqual(s.lists_28_leaders([16, 17, 4, 3, 5, 2]), [17, 5, 2])
        self.assertEqual(s.lists_29_equilibrium_index([1, 3, 5, 2, 2]), 2)
        self.assertEqual(s.lists_30_segregate_zeros_ones([1, 0, 1]), [0, 1, 1])
        self.assertEqual(s.lists_31_sort_zero_one_two([2, 0, 1, 2]), [0, 1, 2, 2])
        self.assertEqual(s.lists_32_product_except_self([1, 2, 3, 4]), [24, 12, 8, 6])
        self.assertEqual(s.lists_33_majority_element([2, 2, 1]), 2)
        self.assertTrue(s.lists_34_is_palindrome([1, 2, 1]))
        self.assertEqual(s.lists_35_sum_squares_of_evens([1, 2, 4]), 20)
        self.assertEqual(s.lists_36_kth_smallest([3, 1, 2], 2), 2)
        self.assertEqual(s.lists_37_insert_and_delete([1, 2, 3], 1, 4, 2), [1, 4, 3])
        self.assertEqual(s.lists_38_longest_consecutive_sequence([100, 4, 200, 1, 3, 2]), 4)
        self.assertEqual(s.lists_39_range([1, 5, 3]), 4)
        self.assertEqual(s.lists_40_marks_above_average([60, 80, 100]), [(2, 100)])


class NumberAndLinkedListTests(unittest.TestCase):
    def test_number_questions(self):
        self.assertTrue(s.maths_01_is_prime(29))
        self.assertEqual(s.maths_02_primes_up_to(10), [2, 3, 5, 7])
        self.assertEqual(s.maths_03_fibonacci_terms(6), [0, 1, 1, 2, 3, 5])
        self.assertEqual(s.maths_04_factorial_iterative(5), 120)
        self.assertEqual(s.maths_04_factorial_recursive(5), 120)
        self.assertEqual(s.maths_05_gcd_lcm(12, 18), (6, 36))
        self.assertEqual(s.maths_06_sum_digits(-123), 6)
        self.assertEqual(s.maths_07_reverse_number(-120), -21)
        self.assertTrue(s.maths_08_is_number_palindrome(1221))
        self.assertTrue(s.maths_09_is_armstrong(153))
        self.assertEqual(s.maths_10_fizzbuzz(5), ["1", "2", "Fizz", "4", "Buzz"])
        self.assertEqual(s.maths_11_digit_count(-100), 3)
        self.assertTrue(s.maths_12_is_perfect(28))
        self.assertTrue(s.maths_13_is_perfect_square(144))
        self.assertEqual(s.maths_14_decimal_to_binary(13), "1101")
        self.assertEqual(s.maths_15_binary_to_decimal("1101"), 13)
        self.assertEqual(s.maths_16_power(2, -3), 0.125)
        self.assertTrue(s.maths_17_even_without_modulo(-4))
        self.assertEqual(s.maths_18_multiplication_table(3, 2), ["3 x 1 = 3", "3 x 2 = 6"])
        self.assertEqual(s.maths_19_sum_natural_numbers(5), (15, 15))
        self.assertEqual(s.maths_20_factors(12), [1, 2, 3, 4, 6, 12])
        self.assertEqual(s.maths_21_prime_factorization(12), [2, 2, 3])
        self.assertTrue(s.maths_22_is_strong_number(145))
        self.assertEqual(s.maths_23_armstrong_numbers(150, 155), [153])
        self.assertEqual(s.maths_24_swap_without_temporary(1, 2), (2, 1))
        self.assertEqual(s.maths_25_largest_of_three(1, 3, 2), 3)
        self.assertTrue(s.maths_26_is_leap_year(2000))
        simple_interest, compound_interest = s.maths_27_interest(100, 10, 2)
        self.assertEqual(simple_interest, 20)
        self.assertAlmostEqual(compound_interest, 21)
        self.assertEqual(s.maths_28_average([1, 2, 3]), 2)
        self.assertEqual(s.maths_29_trailing_zeros_factorial(100), 24)
        self.assertEqual(s.maths_30_collatz_sequence(3), [3, 10, 5, 16, 8, 4, 2, 1])

    def test_linked_list_questions(self):
        head = s.linked_01_from_list([1, 2, 3])
        self.assertEqual(s.linked_01_to_list(head), [1, 2, 3])
        self.assertEqual(s.linked_01_to_list(s.linked_02_insert_beginning(head, 0)), [0, 1, 2, 3])
        self.assertEqual(s.linked_01_to_list(s.linked_02_insert_end(head, 4)), [1, 2, 3, 4])
        head = s.linked_01_from_list([1, 2, 3])
        self.assertEqual(s.linked_01_to_list(s.linked_02_insert_at(s.linked_01_from_list([1, 2, 3]), 1, 9)), [1, 9, 2, 3])
        self.assertEqual(s.linked_01_to_list(s.linked_03_delete_first(s.linked_01_from_list([1, 2, 3]))), [2, 3])
        self.assertEqual(s.linked_01_to_list(s.linked_03_delete_last(s.linked_01_from_list([1, 2, 3]))), [1, 2])
        self.assertEqual(s.linked_01_to_list(s.linked_03_delete_value(s.linked_01_from_list([1, 2, 3]), 2)), [1, 3])
        self.assertEqual(s.linked_04_length(head), 3)
        self.assertTrue(s.linked_05_search(head, 2))
        self.assertEqual(s.linked_07_middle(head).data, 2)
        self.assertEqual(s.linked_01_to_list(s.linked_06_reverse(s.linked_01_from_list([1, 2, 3]))), [3, 2, 1])
        cycle = s.linked_01_from_list([1, 2, 3])
        cycle.next.next.next = cycle.next
        self.assertTrue(s.linked_08_has_cycle(cycle))
        self.assertEqual(s.linked_01_to_list(s.linked_09_merge_sorted(s.linked_01_from_list([1, 3]), s.linked_01_from_list([2, 4]))), [1, 2, 3, 4])
        self.assertEqual(s.linked_01_to_list(s.linked_10_remove_nth_from_end(s.linked_01_from_list([1, 2, 3]), 2)), [1, 3])
        self.assertEqual(s.linked_01_to_list(s.linked_11_remove_sorted_duplicates(s.linked_01_from_list([1, 1, 2]))), [1, 2])
        self.assertTrue(s.linked_12_is_palindrome(s.linked_01_from_list([1, 2, 1])))
        self.assertEqual(s.linked_13_nth_from_end(head, 1), 3)
        self.assertEqual(s.linked_14_values_in_reverse(head), [3, 2, 1])
        self.assertEqual(s.linked_01_to_list(s.linked_15_add_reverse_order_numbers(s.linked_01_from_list([2, 4, 3]), s.linked_01_from_list([5, 6, 4]))), [7, 0, 8])
        shared = s.linked_01_from_list([8, 9])
        left, right = s.linked_01_from_list([1]), s.linked_01_from_list([2])
        left.next, right.next = shared, shared
        self.assertIs(s.linked_16_intersection(left, right), shared)
        self.assertEqual(s.linked_01_to_list(s.linked_17_swap_adjacent_pairs(s.linked_01_from_list([1, 2, 3]))), [2, 1, 3])
        self.assertEqual(s.linked_18_count_value(head, 2), 1)


class RemainingSolutionTests(unittest.TestCase):
    def test_patterns_matrices_and_collections(self):
        self.assertEqual(s.patterns_01_right_triangle(3), ["*", "**", "***"])
        self.assertEqual(s.patterns_02_inverted_right_triangle(2), ["**", "*"])
        self.assertEqual(s.patterns_03_pyramid(2), [" *", "***"])
        self.assertEqual(s.patterns_04_inverted_pyramid(2), ["***", " *"])
        self.assertEqual(s.patterns_05_diamond(2), [" *", "***", " *"])
        self.assertEqual(s.patterns_06_number_triangle(2), ["1", "1 2"])
        self.assertEqual(s.patterns_07_floyd_triangle(2), ["1", "2 3"])
        self.assertEqual(s.patterns_08_pascals_triangle(3), ["1", "1 1", "1 2 1"])
        self.assertEqual(s.patterns_09_hollow_square(3), ["***", "* *", "***"])
        self.assertEqual(s.patterns_10_alphabet_triangle(2), ["A", "A B"])
        matrix = [[1, 2], [3, 4]]
        self.assertEqual(s.matrices_01_rows(matrix), matrix)
        self.assertEqual(s.matrices_02_transpose(matrix), [[1, 3], [2, 4]])
        self.assertEqual(s.matrices_03_add(matrix, matrix), [[2, 4], [6, 8]])
        self.assertEqual(s.matrices_04_multiply(matrix, matrix), [[7, 10], [15, 22]])
        self.assertEqual(s.matrices_05_diagonal_sums(matrix), (5, 5))
        self.assertEqual(s.matrices_06_row_and_column_sums(matrix), ([3, 7], [4, 6]))
        self.assertEqual(s.matrices_07_spiral_order([[1, 2, 3], [4, 5, 6]]), [1, 2, 3, 6, 5, 4])
        self.assertEqual(s.matrices_08_rotate_clockwise(matrix), [[3, 1], [4, 2]])
        self.assertTrue(s.matrices_09_is_symmetric([[1, 2], [2, 1]]))
        self.assertEqual(s.matrices_10_largest_in_each_row(matrix), [2, 4])
        self.assertEqual(s.dictionaries_01_word_frequencies("a b a"), {"a": 2, "b": 1})
        self.assertEqual(s.dictionaries_02_most_frequent_word("a b a"), "a")
        self.assertEqual(s.dictionaries_03_group_anagrams(["eat", "tea", "bat"]), [["eat", "tea"], ["bat"]])
        self.assertEqual(s.dictionaries_04_first_non_repeating([1, 2, 1]), 2)
        self.assertEqual(s.dictionaries_05_merge_sum_values({"a": 1}, {"a": 2, "b": 3}), {"a": 3, "b": 3})
        self.assertEqual(s.dictionaries_06_sort_by_value_descending({"a": 1, "b": 2}), [("b", 2), ("a", 1)])
        self.assertEqual(s.dictionaries_07_invert({"a": 1}), {1: "a"})
        self.assertEqual(s.dictionaries_08_first_not_second([1, 2], [2]), {1})
        self.assertEqual(s.dictionaries_09_topper_and_average({"a": 90, "b": 80}), ("a", 85))
        self.assertTrue(s.dictionaries_10_all_unique([1, 2, 3]))
        self.assertEqual(s.dictionaries_11_pairs_with_difference([1, 3, 5], 2), [(1, 3), (3, 5)])
        self.assertEqual(s.dictionaries_11_pairs_with_difference([2, 2, 3], 0), [(2, 2)])
        self.assertEqual(s.dictionaries_12_vowel_frequencies("Abe"), {"a": 1, "e": 1, "i": 0, "o": 0, "u": 0})

    def test_recursion_files_and_mocks(self):
        self.assertEqual(s.recursion_01_sum_digits(123), 6)
        self.assertEqual(s.recursion_02_factorial(5), 120)
        self.assertEqual(s.recursion_03_fibonacci(7), 13)
        self.assertEqual(s.recursion_04_power(2, 10), 1024)
        self.assertEqual(s.recursion_05_reverse_string("abc"), "cba")
        self.assertTrue(s.recursion_06_is_palindrome("abba"))
        for sort_function in (s.recursion_07_bubble_sort, s.recursion_07_selection_sort, s.recursion_07_insertion_sort, s.recursion_08_merge_sort):
            self.assertEqual(sort_function([3, 1, 2]), [1, 2, 3])
        self.assertEqual(s.recursion_09_linear_search([1, 2], 2), 1)
        self.assertEqual(s.recursion_09_binary_search([1, 2], 2), 1)
        self.assertEqual(s.recursion_10_tower_of_hanoi(2), [("A", "B"), ("A", "C"), ("B", "C")])
        self.assertEqual(len(s.recursion_11_permutations("abc")), 6)
        self.assertEqual(s.recursion_12_subsets([1, 2]), [[], [1], [2], [1, 2]])
        with tempfile.TemporaryDirectory() as directory:
            source = Path(directory) / "input.txt"
            target = Path(directory) / "copy.txt"
            source.write_text("one two\nthree\n", encoding="utf-8")
            self.assertEqual(s.files_01_count_text(source), {"lines": 2, "words": 3, "characters": 14})
            s.files_02_write_items(target, ["a", "b"])
            self.assertEqual(target.read_text(encoding="utf-8"), "a\nb\n")
            source.write_text("1 2 3", encoding="utf-8")
            self.assertEqual(s.files_03_sum_numbers(source), 6)
            s.files_04_copy(source, target)
            self.assertEqual(target.read_text(encoding="utf-8"), "1 2 3")
        self.assertEqual(s.files_05_sum_input_line("1 2 3"), 6)
        self.assertEqual(s.files_06_reverse_lines(["a", "b"]), ["b", "a"])
        self.assertEqual(s.files_07_format_name_age("Ada", 36), "My name is Ada and I am 36 years old.")
        self.assertEqual(s.files_08_parse_csv_integers("1, 2,3"), [1, 2, 3])
        self.assertEqual(s.mock_01_words_sorted_by_length("a four two"), [("four", 4), ("two", 3), ("a", 1)])
        self.assertEqual(s.mock_02_kth_largest_distinct([1, 3, 3, 2], 2), 2)
        self.assertEqual(s.mock_03_reverse_remove_value([1, 2, 1], 1), [2])
        self.assertEqual(s.mock_04_most_frequent_character("abaca"), ("a", 3))
        self.assertEqual(s.mock_05_longest_zero_sum_subarray([1, -1, 3, 2, -2]), 2)
        self.assertEqual(s.mock_06_anagram_differences("ab", "ac"), (False, {"b": 1, "c": -1}))
        self.assertEqual(s.mock_07_matrix_summaries([[1, 2], [3, 4]]), ([3, 7], [4, 6], (1, 1)))
        self.assertEqual(s.mock_08_bracket_error_index("([)]"), 2)
        self.assertEqual(s.mock_08_bracket_error_index("(()"), 0)
        self.assertEqual(s.mock_09_second_salary_and_average([("A", 100), ("B", 90), ("C", 90)]), ("B", 93.33))
        self.assertEqual(s.mock_10_unique_pairs_with_sum([1, 2, 3, 4], 5), [(1, 4), (2, 3)])

    def test_pandas_and_numpy_questions(self):
        import numpy as np
        import pandas as pd

        with tempfile.TemporaryDirectory() as directory:
            csv_path = Path(directory) / "data.csv"
            pd.DataFrame({"group": ["a", "a", "b"], "value": [1.0, 3.0, np.nan]}).to_csv(csv_path, index=False)
            head, shape, dtypes = s.pandas_01_load_csv_summary(csv_path)
            self.assertEqual(head.shape, (3, 2))
            self.assertEqual(shape, (3, 2))
            self.assertEqual(list(dtypes.index), ["group", "value"])

        frame = pd.DataFrame({
            "group": ["a", "a", "b", "b"],
            "value": [1.0, 3.0, np.nan, 5.0],
            "extra": [2, 4, 6, 8],
            "date": ["2026-01-01", "2026-02-01", "2026-02-15", "2026-03-01"],
        })
        self.assertEqual(s.pandas_02_filter_above(frame, "value", 2)["value"].tolist(), [3.0, 5.0])
        self.assertEqual(s.pandas_03_missing_counts(frame)["value"], 1)
        filled = s.pandas_04_fill_numeric_means(frame)
        self.assertEqual(filled["value"].isna().sum(), 0)
        self.assertEqual(s.pandas_05_drop_duplicates(pd.concat([frame, frame.iloc[[0]]])).shape[0], 4)
        aggregate = s.pandas_06_group_aggregates(frame.dropna(), "group", "value")
        self.assertEqual(aggregate.loc["a", "mean"], 2)
        self.assertEqual(s.pandas_07_sort_descending(frame.dropna(), "value")["value"].tolist(), [5.0, 3.0, 1.0])
        self.assertEqual(s.pandas_08_add_columns(frame, "combined", "value", "extra")["combined"].iloc[0], 3)
        merged = s.pandas_09_merge(pd.DataFrame({"key": [1]}), pd.DataFrame({"key": [1], "x": [2]}), "key")
        self.assertEqual(merged.loc[0, "x"], 2)
        self.assertEqual(s.pandas_10_top_frequencies(pd.DataFrame({"x": ["a", "a", "b"]}), "x").iloc[0], 2)
        self.assertEqual(s.pandas_11_month_from_datetime(frame, "date")["month"].tolist(), [1, 2, 2, 3])
        correlated = pd.DataFrame({"x": [1, 2, 3], "y": [2, 4, 6]})
        self.assertAlmostEqual(s.pandas_12_correlation(correlated, "x", "y"), 1)
        mean, median, standard_deviation = s.numpy_13_summary([1, 2, 3])
        self.assertEqual((mean, median), (2, 2))
        self.assertAlmostEqual(standard_deviation, np.std([1, 2, 3]))
        matrix, transpose, row_sums = s.numpy_14_matrix_summary()
        self.assertEqual(matrix.shape, (3, 3))
        self.assertTrue(np.array_equal(transpose, matrix.T))
        self.assertTrue(np.array_equal(row_sums, [6, 15, 24]))


if __name__ == "__main__":
    unittest.main()
